apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: inventory-quarkus-cnw3-7xwb
  namespace: agroom-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:ZzBzx-inventory-quarkus-cnw3-7xwb
        name: my-java-quarkus
        resources: {}
status: {}
