apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gateway-vertx-cnw3-pywg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gateway-vertx-cnw3-pywg
    app.kubernetes.io/part-of: cnw3
  name: gateway-vertx-cnw3-pywg
  namespace: agroom-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: gateway-vertx-cnw3-pywg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: gateway-vertx-cnw3-pywg
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:ZzBzx-gateway-vertx-cnw3-pywg
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
