apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gateway-vertx-cnw3-pywg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gateway-vertx-cnw3-pywg
    app.kubernetes.io/part-of: cnw3
  name: gateway-vertx-cnw3-pywg
  namespace: agroom-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: gateway-vertx-cnw3-pywg
status:
  loadBalancer: {}
