apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: catalog-spring-gradle-cnw3-wnj1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: catalog-spring-gradle-cnw3-wnj1
    app.kubernetes.io/part-of: cnw3
  name: catalog-spring-gradle-cnw3-wnj1
  namespace: agroom-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: catalog-spring-gradle-cnw3-wnj1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: catalog-spring-gradle-cnw3-wnj1
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:ZzBzx-catalog-spring-gradle-cnw3-wnj1
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
