apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: catalog-spring-gradle-cnw3-wnj1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: catalog-spring-gradle-cnw3-wnj1
    app.kubernetes.io/part-of: cnw3
  name: catalog-spring-gradle-cnw3-wnj1
  namespace: agroom-tenant
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: catalog-spring-gradle-cnw3-wnj1
status:
  loadBalancer: {}
