apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: faas-cnw3-hlqx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: faas-cnw3-hlqx
    app.kubernetes.io/part-of: cnw3
  name: faas-cnw3-hlqx
  namespace: agroom-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: faas-cnw3-hlqx
    weight: null
status: {}
