apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: gateway-vertx-cnw3-pywg
  namespace: agroom-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:ZzBzx-gateway-vertx-cnw3-pywg
        name: my-java-quarkus
        resources: {}
status: {}
