apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: web-nodejs-cnw3-zsld
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: web-nodejs-cnw3-zsld
    app.kubernetes.io/part-of: cnw3
  name: web-nodejs-cnw3-zsld
  namespace: agroom-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: web-nodejs-cnw3-zsld
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: web-nodejs-cnw3-zsld
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:ZzBzx-web-nodejs-cnw3-zsld
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
