apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: web-nodejs-cnw3-zsld
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: web-nodejs-cnw3-zsld
    app.kubernetes.io/part-of: cnw3
  name: web-nodejs-cnw3-zsld
  namespace: agroom-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: web-nodejs-cnw3-zsld
    weight: null
status: {}
