apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: inventory-quarkus-cnw3-7xwb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: inventory-quarkus-cnw3-7xwb
    app.kubernetes.io/part-of: cnw3
  name: inventory-quarkus-cnw3-7xwb
  namespace: agroom-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: inventory-quarkus-cnw3-7xwb
status:
  loadBalancer: {}
