apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: catalog-spring-boot-cnw3-2ncj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: catalog-spring-boot-cnw3-2ncj
    app.kubernetes.io/part-of: cnw3
  name: catalog-spring-boot-cnw3-2ncj
  namespace: agroom-tenant
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: catalog-spring-boot-cnw3-2ncj
status:
  loadBalancer: {}
